name: CI

on:
  push:
    branch:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
    - name: Build assets
      run: yarn build
    - name: Deploy to github pages
      env:
        GIT_AUTHOR_NAME: Thierry Deo
        GIT_AUTHOR_EMAIL: thierry.deo@gmail.com
        GIT_COMMITTER_NAME: Thierry Deo
        GIT_COMMITTER_EMAIL: thierry.deo@gmail.com
        EMAIL: thierry.deo@gmail.com
      run: |
        yarn exec gh-pages -- \
          -r https://tdeo:${{ secrets.GITHUB_PERSONNAL_ACCESS_TOKEN }}@github.com/tdeo/tdeo.github.io \
          -d build \
          -b master
