name: CI

on:
  push:
    branch:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
    - name: Build assets
      run: yarn build
    - name: Deploy to github pages
      run: |
        yarn exec gh-pages -- \
          -r https://tdeo@{{ secrets.GH_PAT }}/tdeo/tdeo.github.io.git \
          -d build \
          -b master
