name: CI

on:
  push:
    branch:
    - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Run a multi-line script
      run: |
        yarn install
        yarn build
    - name: Deploy to github pages
      uses: maxheld83/ghpages@v0.2.1
      with:
        BUILD_DIR: build/
